replicaCount: ${{ values.replica_count }}

image:
  repository: 454143665149.dkr.ecr.ap-south-1.amazonaws.com/${{ values.app_name }}
  pullPolicy: IfNotPresent
  tag: 

resources:
  requests:
    cpu: ${{ values.cpu_request }}
    memory: ${{ values.memory_request }}