apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that displays time.
  annotations:
    github.com/project-slug: vanraj-boricha/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    prometheus.io/rule: 'sum(rate(container_cpu_usage_seconds_total{container="${{values.app_name}}"}[5m]))|CPU Load,container_memory_working_set_bytes{container="${{values.app_name}}"}|Memory Usage,rate(http_requests_total{container="${{values.app_name}}"}[5m])|HTTP Request Rate,rate(http_errors_total{container="${{values.app_name}}"}[5m])|HTTP Error Rate'
    prometheus.io/alert: 'KubePodCrashLooping'
    argocd/app-name: ${{values.app_name}}
    argocd/instance-name: main
    grafana/dashboard-selector: '"${{ values.app_name }}" in tags'
    grafana/alert-label-selector: "app=${{ values.app_name }}"
    sonarqube.org/project-key: vanraj-boricha_${{ values.app_name }}
spec:
  type: service
  owner: development
  lifecycle: experimental
