# ── Base default values ────────────────────────────────────────────
replicaCount: 1

image:
  repository: ${{ values.ecr_repo }}
  pullPolicy: Always
  tag: "latest"               # overridden by CI/CD with short SHA

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: ${{ values.port }}

ingress:
  enabled: false
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    # 2. Attach your custom Security Group ID
    #alb.ingress.kubernetes.io/security-groups: sg-069a3b19f094012ae
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  - name: PORT
    value: "${{ values.port }}"
  - name: NODE_ENV
    value: "production"

livenessProbe:
  httpGet:
    path: /health
    port: ${{ values.port }}
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: ${{ values.port }}
  initialDelaySeconds: 5
  periodSeconds: 10

monitoring:
  # Dump ensures boolean values don't break YAML parsing
  enabled: ${{ values.enable_prometheus | dump }}
  portName: http
  metricsPath: ${{ values.prometheus_metrics_path | default("/metrics") }}
  scrapeInterval: ${{ values.prometheus_scrape_interval | default("15s") }}
  scrapeTimeout: 10s
  dashboard:
    enabled: ${{ values.enable_prometheus | dump }}
  alerting:
    enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
