replicaCount: 2

image:
  repository: ${{ values.ecr_repo }}
  pullPolicy: Always
  tag: "latest"              # updated by yq in CD pipeline

service:
  type: ClusterIP
  port: 80
  targetPort: ${{ values.port }}

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    # 1. Change from 'internal' to 'internal'
    alb.ingress.kubernetes.io/scheme: internal
    # 2. Attach your custom Security Group ID
    #alb.ingress.kubernetes.io/security-groups: sg-069a3b19f094012ae
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  - name: PORT
    value: "${{ values.port }}"
  - name: NODE_ENV
    value: "staging"

monitoring:
  # Dump ensures boolean values don't break YAML parsing
  enabled: ${{ values.enable_prometheus | dump }}
  portName: http
  metricsPath: ${{ values.prometheus_metrics_path | default("/metrics") }}
  scrapeInterval: ${{ values.prometheus_scrape_interval | default("15s") }}
  scrapeTimeout: 10s
  dashboard:
    enabled: ${{ values.enable_prometheus | dump }}
  alerting:
    enabled: ${{ values.enable_prometheus | dump }}
    memoryThresholdBytes: 500000000
    cpuThresholdPercent: 80